"on":
  pull_request:
    types:
    - closed
name: Porter Preview Environment
jobs:
  porter-delete-preview:
    runs-on: ubuntu-latest
    steps:
    - name: Delete Porter preview env
      timeout-minutes: 30
      uses: porter-dev/porter-delete-preview-action@master
      with:
        cluster: "5"
        host: https://dashboard.dev.getporter.dev
        installation_id: "21273036"
        namespace: pr-${{ github.event.pull_request.number }}-go-getting-started
        project: "3"
        repo_name: go-getting-started
        repo_owner: ${{ github.repository_owner }}
        token: ${{ secrets.PORTER_TOKEN_3 }}
